### ISSUE TITLE
Tick icon on button at start up

### ISSUE THREAD

**Issue by nsleigh** [cgiesche/streamdeck-homeassistant#145] opened 2023-04-01 09:02 UTC
Whenever the StreamDesk application starts 3 of my HASS linked buttons display a tick icon over the correct icon and then when you press the button it reverts to the correct icon. I have other HASS buttons that don't do this. One of the buttons is a script domain the other 2 are mediaplayer.

Tick icon
![image](https://user-images.githubusercontent.com/7244133/229276551-fbd198f7-57c7-4016-be14-7a82d3485e1f.png)
Correct icon
![image](https://user-images.githubusercontent.com/7244133/229276592-3f60edc3-9175-4312-8f97-a9ffb169443b.png)

Any ideas what is causing this?

**Comment by cgiesche** [comment] 2023-04-01 09:49
I have noticed this on some of my buttons (sometimes, not often), too. It _may_ be fixed with the next release.
I will come back to this after the release.

**Comment by tonka3000** [comment] 2023-04-02 13:50
Hi,

I have the same issue since the latest streamdeck update. It affect all my entities on the streamdeck XL.
Interestingly I have some buttons left with the old version (which could not installed through the store) and they work normally.

**Comment by nsleigh** [comment] 2023-04-13 06:37
If it helps I have also noticed the icons change when when HA restarts but usually goes back to the correct icons.

**Comment by arendon1** [comment] 2023-05-03 07:36
You should be able to get rid of it, changing the settings for the Stream Deck app. I'll attach some reference images, they're in Spanish though but should be familiar enough to follow.

![image](https://user-images.githubusercontent.com/1384026/235856119-1a969609-40a4-4432-a93f-b179bc8e12dc.png)
![image](https://user-images.githubusercontent.com/1384026/235856470-d3b6360a-1710-48af-902e-a55d02e4006e.png)

**Comment by nsleigh** [comment] 2023-05-03 11:14
Afraid that didn't work for me.

**Comment by tonka3000** [comment] 2023-05-03 11:56
Didn't work for me as well.

**Comment by arendon1** [comment] 2023-05-03 14:03
Oh, my bad. I'm sorry. well, I supposed we need to wait feedback from dev then.

**Comment by pickett** [comment] 2023-05-05 19:13
I have this issue as well. For me it doesn't have to do with Home Assistant restarting, it actually is fairly easy to reproduce by sleeping and waking my Mac.

1. Tap buttons to make sure the checkmark disappears.
2. Put Mac to sleep
3. Wake Mac back up.
Result: Green icons.

**Comment by pickett** [comment] 2023-05-05 19:17
Oh and, just now while testing this, I discovered a workaround that seems to work for me. If you put the Home Assistant Entity within a multi-action, even if there is just one single action, the green check won't show at start. I did disable "Show Progress Overlay" for the multi-action within settings as suggested by @arendon1.

**Comment by nsleigh** [comment] 2023-05-07 08:42
"multi-action" method worked for me too, bit of a pain to setup but I can live with it.

**Comment by jefft4** [comment] 2023-05-30 13:25
Same problem here; Windows 11.  Big green circle and tick across most of my HA buttons at startup, until they're pressed.  Oddly, one button doesn't have the tick.  Sensors are okay.

**Comment by ericpenn** [comment] 2023-06-05 17:39
This kind of makes the Stream Deck useless to me... Giant green checkmark over almost all my icons.... If you press the button or move the icon to another spot it goes away and looks good again, but within a short period of time they all come back! Looks like hell...

**Comment by ericpenn** [comment] 2023-06-11 16:38
I'm guessing since it's been five months now, this project is dead.  Wish I knew that before I bought this... What's the point of even having a screen if they all have giant check marks covering them... Good idea, but heading to the trash can...

**Comment by cgiesche** [comment] 2023-06-11 17:16
You can be sure I am doing my best to keep this project alive.
As I am currently a one man show with limited types of hardware (in fact a single windows PC and a server running home assistant) it is not easy to fix a big, that does not appear on my device.
One thing I can try is to remove the whole "checkmark feature" which is normally intended to let the user know, the server connection has been (re-)established.
With the latest release, i did some rework regarding the websocket connection and I hoped, this could have fixed this issue, too.
unfortunately it did not...

**Comment by ericpenn** [comment] 2023-06-11 21:11
Thank you for reaching out.  I've removed the comment. It is a very good product/software, but just becomes frustrating when it doesn't work as expected. Thanks again.  
Eric-
    On Sunday, June 11, 2023 at 01:16:22 PM EDT, Christoph Giesche ***@***.***> wrote:  
 
 


You can be sure I am doing my best to keep this project alive.
As I am currently a one man show with limited types of hardware (in fact a single windows PC and a server running home assistant) it is not easy to fix a big, that does not appear on my device.
One thing I can try is to remove the whole "checkmark feature" which is normally intended to let the user know, the server connection has been (re-)established.
With the latest release, i did some rework regarding the websocket connection and I hoped, this could have fixed this issue, too.
unfortunately it did not...

**Comment by jefft4** [comment] 2023-06-19 12:28
> You can be sure I am doing my best to keep this project alive. As I am currently a one man show with limited types of hardware (in fact a single windows PC and a server running home assistant) it is not easy to fix a bug, that does not appear on my device. One thing I can try is to remove the whole "checkmark feature" which is normally intended to let the user know, the server connection has been (re-)established. With the latest release, i did some rework regarding the websocket connection and I hoped, this could have fixed this issue, too. unfortunately it did not...

Interesting that you don't experience the problem; I also am running a Windows PC and a HA server (on Ubuntu).  Are there any diagnostics I can provide that would help us to work out how my system and yours differ and from that, maybe the root cause?

**Comment by cgiesche** [comment] 2023-06-22 19:44
Hello everyone,

can one of you please check out this (experimental) release: https://github.com/cgiesche/streamdeck-homeassistant/releases/tag/2.3.2

The only difference to the current store version is that i removed the checkmark as it seems to be buggy.

**Comment by ericpenn** [comment] 2023-06-22 22:36
Hello Christoph.
So I have a new PC build. Installed Stream and your Beta insert above.  I created a new token and it seems to connect fine.  All my Ha stuff is showing up. When I create a button and press it, nothing happens.  Also if I create a button with like a temperature, it does not show up, just the HAS icon. I tried both Entity Generic and Custom. Attached are screen shots.   It's could be me, of course...
Eric
    On Thursday, June 22, 2023 at 12:44:35 PM PDT, Christoph Giesche ***@***.***> wrote:  
 
 


Hello everyone,

can one of you please check out this (experimental) release: https://github.com/cgiesche/streamdeck-homeassistant/releases/tag/2.3.2

The only difference to the current store version is that i removed the checkmark as it seems to be buggy.

**Comment by ericpenn** [comment] 2023-06-22 22:46
Never Mind, it started working... I'll let you know in a few days the results. Thanks again!
Eric-

    On Thursday, June 22, 2023 at 03:36:10 PM PDT, Eric Smith ***@***.***> wrote:  
 
  Hello Christoph.
So I have a new PC build. Installed Stream and your Beta insert above.  I created a new token and it seems to connect fine.  All my Ha stuff is showing up. When I create a button and press it, nothing happens.  Also if I create a button with like a temperature, it does not show up, just the HAS icon. I tried both Entity Generic and Custom. Attached are screen shots.   It's could be me, of course...
Eric
    On Thursday, June 22, 2023 at 12:44:35 PM PDT, Christoph Giesche ***@***.***> wrote:  
 
 


Hello everyone,

can one of you please check out this (experimental) release: https://github.com/cgiesche/streamdeck-homeassistant/releases/tag/2.3.2

The only difference to the current store version is that i removed the checkmark as it seems to be buggy.

**Comment by ericpenn** [comment] 2023-06-25 00:40
Seems to be working good!  Thank you!.
Only thing I want to bring to your attention is most likely my not understanding things here. 
Under 'button settings" there is a field for "Entity (Optional)". Seems the only way my HA things actually work is if I repeat the entity in this field. If left empty the button doesn't work.  See attached.
With that said, yes this beta works good so far. Icons are staying in tact and buttons work good.
Eric-

    On Thursday, June 22, 2023 at 12:44:35 PM PDT, Christoph Giesche ***@***.***> wrote:  
 
 


Hello everyone,

can one of you please check out this (experimental) release: https://github.com/cgiesche/streamdeck-homeassistant/releases/tag/2.3.2

The only difference to the current store version is that i removed the checkmark as it seems to be buggy.

**Comment by cgiesche** [comment] 2023-06-26 13:04
> Only thing I want to bring to your attention is most likely my not understanding things here. 
> Under 'button settings" there is a field for "Entity (Optional)". Seems the only way my HA things actually work is if I repeat the entity in this field. If left empty the button doesn't work.  See attached.

This is a new feature that was already part of the previous release: It enables you to use different entities for the display and the triggered action of the button. (For exampe: Show weather on the button, trigger lights on button press.

**Closed** 2023-06-30 13:03 UTC

**Comment by tonka3000** [comment] 2023-07-01 09:39
Works with the latest pre-release. Thanks @cgiesche

**Comment by AlxSZP** [comment] 2023-11-03 01:46
@cgiesche Also just installed 2.3.3 pre-release on:
- macOS Sonoma 14.1
- mac Mini M2 Pro 
- Stream Deck XL 

Everything is working great!

Tests:
Set computer to sleep -> Wake Up
- [x] No green checkmarks!
Closed "elgato Stream Deck.app" -> Open app
- [x] No green checkmarks!

Plugin features:
- [x] Generic Toggle
- [x] light scenes
- [x] Sensor data display
- [x] Fan controls
- [x] Climate data display 

If you want me to run any other tests, do let me know! happy to help with my specific setup

**Comment by cgiesche** [comment] 2023-11-05 23:31
Thank you very much for your help!
