### ISSUE TITLE
% values not display

### ISSUE THREAD

**Issue by BryanB0** [cgiesche/streamdeck-homeassistant#129] opened 2023-01-25 12:48 UTC
Hello,
Since the last update of the stream deck (6.0.2) the data in % no longer works and is no longer displayed on the stream deck.

![image](https://user-images.githubusercontent.com/50143034/214566858-930d0c68-effd-4913-b5a4-22dfd7d5b12a.png)

![image](https://user-images.githubusercontent.com/50143034/214567148-cbfc4dc0-05fc-4279-9223-4cf61d666aa7.png)

![image](https://user-images.githubusercontent.com/50143034/214566742-60f80966-e382-432c-8e3b-8b85808b280c.png)

**Comment by cgiesche** [comment] 2023-01-25 12:52
Hi Bryan, 

i know about this issue, but i don't know (yet) why it exists and how to fix it :/. Until I found out, you can work around this issue by enabling "custom labels" and enter only {{state}} without "%".

I will close this issue, because it is a duplicate of #114.

**Closed by cgiesche** 2023-01-25 12:52 UTC
