### ISSUE TITLE
Unit of measurement %

### ISSUE THREAD

**Issue by Olli2k** [cgiesche/streamdeck-homeassistant#171] opened 2023-08-03 14:41 UTC
I just notice that every entity with unit of measurement "%" (percent) is not working.
Tried to figure it out with custom label.

{{state}} {{ ["!"] }} << is working
{{state}} {{ ["%"] }} << is not working

![grafik](https://github.com/cgiesche/streamdeck-homeassistant/assets/22831306/56f555a6-2bba-42ff-8b71-cb590a0cb610)
![grafik](https://github.com/cgiesche/streamdeck-homeassistant/assets/22831306/e0b4069b-ae08-48ba-b2f1-6e54c677f52d)

**Comment by cgiesche** [comment] 2023-08-03 15:23
Hello!

You may try the latest pre-release from here (Normally can be installed by doubleclicking .sdplugin file): https://github.com/cgiesche/streamdeck-homeassistant/releases/tag/2.3.4
When this or a newer version is released to the elgato store, it will be automatically updated.

**Comment by cgiesche** [comment] 2023-08-09 08:15
Duplicate of #139

**Closed by cgiesche** 2023-08-09 08:15 UTC
