### ISSUE TITLE
Information Not Saving 

### ISSUE THREAD

**Issue by rainman369** [cgiesche/streamdeck-homeassistant#59] opened 2021-11-28 18:23 UTC
I configure everything (websocket address, token) and it seems to connect to the server. I configure the entity, in this case a light toggle, and click save config. However, when I click off of the newly created button and then back on, everything is blank. Have tried this multiple times and it doesn't seem to save anything inside the button text fields.

**Comment by gtrabanco** [comment] 2021-11-30 23:16
It is important when you report an issue say OS, OS Version and StreamDeck Version.

It is also important say the steps to reproduce the issue, you could be doing something different that the coder did not think about it or you could be missing a step.

**Comment by jimmyeao** [comment] 2021-12-02 09:17
I also have this
Windows 11 Build 22000.348
Stream Deck 5.1.3.14750
Steps to reproduce:
Enter URL and Key, and save, select entity and action, then save
Result: Initialy works, but following a reboot, the details are wiped out and it will not save them again (Allows you to enter them and select entities, but as soon as you navigate away from that icon and back again, the settings have gone)

**Comment by cgiesche** [comment] 2021-12-02 09:25
Ok, that sounds strange. I will check if I can reproduce the issus. Maybe something changed with the latest stream-deck application update.
I am using this plugin on Windows 11 and Stream Deck 5.1.2.14743 without any issuse. I will upgrade my stream deck application and see, what happens.

**Comment by cgiesche** [comment] 2021-12-02 09:38
Hmm, works for me with the newest version of stream deck.
@jimmyeao Are you coming from a "fresh" (first use) plugin installation, or did you use it before and it broke just now? My personal installation has gone through every mini-upgrade of the plugin. Maybe this problem is related to first-time-installations.

**Comment by edgard** [comment] 2021-12-05 02:57
Same here. Same build versions for Windows and StreamDeck software.

**Comment by jimmyeao** [comment] 2021-12-05 14:12
> Hmm, works for me with the newest version of stream deck.
> @jimmyeao Are you coming from a "fresh" (first use) plugin installation, or did you use it before and it broke just now? My personal installation has gone through every mini-upgrade of the plugin. Maybe this problem is related to first-time-installations.

I used it before, happy to do whatever you need to aid In trouble shooting

**Comment by rainman369** [comment] 2021-12-06 12:30
In my case - I did not get notified about an updated version available for the SD; upgrading the software solved the issue I was having with the plugin. Oops :D @cgiesche , I am not closing since someone else commented on here with an issue, but feel free to close it out if you wish! Sorry for the erroneous report.

**Comment by edgard** [comment] 2021-12-06 12:43
So that was it. My plugin was on version 1.4.0 still. Upgrading it manually to 1.5.1 made it work.

**Comment by rainman369** [comment] 2021-12-06 12:47
> So that was it. My plugin was on version 1.4.0 still. Upgrading it manually to 1.5.1 made it work.

I am used to software notifying/demanding to be updated lol Stream Deck apparently doesn't care :)

**Comment by cgiesche** [comment] 2021-12-06 13:19
> I am used to software notifying/demanding to be updated lol Stream Deck apparently doesn't care :)
I think this is because my plugin is not being installed via the Stream Deck "store", so it is more or less my fault. When i started this project, it was a "manual email process" to get plugins into the store. I will re-check if this changed and maybe publish this plugin "officially".

However, i have no idea, why the 1.4.0 version stopped working 🤔.

**Comment by jimmyeao** [comment] 2021-12-06 13:24
So I need to test this, but looks like downloading and double clicking the release version doesn't "upgrade" you fully.
I quit stream deck, then extracted it with 7-zip and copied into 
`%AppData%\Roaming\Elgato\StreamDeck\Plugins\de.perdoctus.streamdeck.ha.sdPlugin`
and restarted stream deck, this appears to have worked so far - ill report back when ive done a reboot

**Comment by cgiesche** [comment] 2021-12-28 10:32
I will close this issue for now. If the problem reappears, feel free to reopen it :)

**Closed by cgiesche** 2021-12-28 10:32 UTC
