### ISSUE TITLE
Phone Battery level does not work after Stream Deck software Update

### ISSUE THREAD

**Issue by ronjtaylor** [cgiesche/streamdeck-homeassistant#138] opened 2023-03-18 01:04 UTC
After updating to latest software the Home assistant Plug-In does not report Battery Level of my Samsung Phone any more.
![image](https://user-images.githubusercontent.com/46874942/226074804-cdb0a1ff-0130-4930-a5e9-1d0c11456313.png)

![image](https://user-images.githubusercontent.com/46874942/226074859-c1df1383-acd3-44f4-9f89-92ad5786a9c8.png)

I have checked the sensor in HA and it is reporting the Phone Battery level in HA correctly.
Other features of the Plugin still seem to work OK.
Can you help or is this a bug?

**Comment by LuckyNils** [comment] 2023-03-20 10:04
Same here. Weather and Phone Battery level dont work anymore. Anything else works (for example Battery Health)

**Comment by arthurEspooner** [comment] 2023-03-20 17:07
looks like it's related to #139 which i think has been an issue before

**Comment by cgiesche** [comment] 2023-03-29 21:04
Closing this isssue (not fixed) as duplicate of https://github.com/cgiesche/streamdeck-homeassistant/issues/139 (Workaround inside!).

**Closed by cgiesche** 2023-03-29 21:04 UTC
