### ISSUE TITLE
Addon keeps disconnecting

### ISSUE THREAD

**Issue by ggflempire** [cgiesche/streamdeck-homeassistant#193] opened 2023-11-29 16:16 UTC
Hello, 

Am I the only one having issues with the addon keeps disconnecting? For me to use it I need to open stream deck app, go to one of my Home Assistant buttons, and click "Reconnect" then it works for a while again. When it stops working I need to  do the same again (reconnect)

I am using this on Windows. I have not tried to re-install or anything yet. Wanted to hear if this is a bug or my system that there is issues with...

**Comment by cgiesche** [comment] 2023-11-29 16:29
Hi,

it was a bug (I think). Since the update has not yet been published to the store, you may want to try the latest version from here.

Installing the plugin manually is safe and it will update automatically from legato store as soon as a newer version is released.

**Comment by Japh** [comment] 2023-12-17 23:35
I'm so glad to come here and find a solution! Although, this issue was opened 3 weeks ago, and I'm assuming the update still isn't published in the Elgato store? That's a shame. Do they have a regular cadence for publishing updates usually, or seems ad-hoc?

**Comment by joestump** [comment] 2023-12-23 03:27
Unsure if this is related or not, but I got a Stream Deck+ recently, configured it and twice now it's stopped sending commands. The UI responds immediately when I use Home Assistant or a remote to change the volume. 

I've tried everything I can think of:

* Different computer
* Unplug, replugin, waiting minutes with it powered down
* Clicking Reconnect on multiple buttons
* Intentionally failing the connection and reconnecting successfully
* Different profile
* New profile, new connection
* Uninstall plugin, reinstall
* Uninstall entire Stream Deck software, reinstall
* Reboot host computer
* Reboot HASS

The issue persists. UI responds immediately, but knobs/button presses do nothing. I can confirm by the Last Activated field that the Home Assistant scenes are not being called. It effects all entity types I'm trying to use.

The Stream Deck works fine otherwise, including buttons I've mapped to open folders, back buttons, and open Steam on my PC.

**Comment by cgiesche** [comment] 2024-01-11 11:43
Fixed in latest release. (#277 is a different issue)

**Closed by cgiesche** 2024-01-11 11:43 UTC
Labels: bug
